# .circleci/config.yml
version: 2.1
jobs:
  beta_android:
    docker:
      - image: cimg/android:2024.04
      - checkout
      - run: yarn deploy_android_beta

workflows:
  deploy-workflow:
    jobs:
      - beta_android
