# .circleci/config.yml
version: 2.1
jobs:
  beta_android:
    docker:
      - image: cimg/android:2024.01.1-node
    steps:
      - checkout
      - echo BASE64_KEYSTORE | base64 -d > cicd-project-upload-key.keystore
      - run: yarn deploy_android_beta base64-keystore: BASE64_KEYSTORE

workflows:
  deploy-workflow:
    jobs:
      - beta_android
