# .circleci/config.yml
version: 2.1
jobs:
  beta_android:
    docker:
      - image: circleci/android:api-30-node
    steps:
      - checkout
      - yarn deploy_android_beta

workflows:
  deploy-workflow:
    jobs:
      - beta_android
