# .circleci/config.yml
version: 2.1
jobs:
  try-job:
    macos:
      xcode: 14.0.1
    steps:
      - checkout
      - run: echo "Im a job test within a workflow test"

workflows:
  test-workflow:
    jobs:
      - try-job
