# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
    print('faslane works on android')
  end

  desc "Prepare android release build"
  lane :build_android do
    gradle(
      task: "assembleRelease",
)
  end

  desc "Prepare android build and distribute the APK  to the firebaseappdistribution"
  lane :beta_android do
    build_android
    firebase_app_distribution(
      app: "1:98501032017:android:9485725a98e50c8472e070",
      firebase_cli_token: "1//09nmPTigFhf6iCgYIARAAGAkSNwF-L9Ir_HUgdfOVRYuYPKAeVSFeRw66zJXUyo-AmQfvdQ4MUUnxkYUtpjWhd82x9f9zZ20YZ44",
      groups: "my-testers"
    )
  end
end
